In [1]:
#Funcoes com a biblioteca Pandas

import pandas as pd
alunos = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4, 7, 5.5, 9], 
          'Aprovado':['Nao', 'Sim', 'Nao', 'Sim']}

In [2]:
#Transformando lista em um dataframe
dataframe = pd.DataFrame(alunos)

In [3]:
print (dataframe)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim


In [4]:
objeto1 = pd.Series([2, 6, 9, 10, 5])
print(objeto1)

0     2
1     6
2     9
3    10
4     5
dtype: int64


In [5]:
import numpy as np
array2 = np.array([(2, 6, 9, 10, 5), (0, 12, 2, 9, 10)])
array1 = np.array([2, 6, 9, 10, 5])
print(array1)
print(array2)

[ 2  6  9 10  5]
[[ 2  6  9 10  5]
 [ 0 12  2  9 10]]


In [6]:
objeto2 = pd.Series(array1)
print(objeto2)

0     2
1     6
2     9
3    10
4     5
dtype: int32


In [8]:
#Aula13 Continuação das funçoes do Pandas
import pandas as pd
alunosDIC = {'Nome':['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Nota':[4, 7, 5.5, 9], 
          'Aprovado':['Nao', 'Sim', 'Nao', 'Sim']}

In [9]:
alunosDF = pd.DataFrame(alunosDIC)

In [10]:
print(alunosDF)

      Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim


In [11]:
#comando Head() Mostra o cabeçalho da tabela carregada
alunosDF.head()

Nome  Nota Aprovado
0  Ricardo   4.0      Nao
1    Pedro   7.0      Sim
2  Roberto   5.5      Nao
3   Carlos   9.0      Sim

In [13]:
#descobrir o tamanho do dataframe no formato (linhas, colunas)
alunosDF.shape

(4, 3)

In [19]:
#gerando informações dos dados numéricos do dataframe
alunosDF.describe()

Nota
count  4.000000
mean   6.375000
std    2.136001
min    4.000000
25%    5.125000
50%    6.250000
75%    7.500000
max    9.000000